__default__:
    time: 00:30:00
    job-name:  LabQC
    account: project_2001746
    ntasks: 1
    cpus-per-task: 1
    mem-per-cpu: 4000
    partition: small
    working-directory: /scratch/project_2001746/logs/
    nvme: 0

# Module 1- Preprocessing
################################################################################
fastp_trim_reads:
    job-name: fastp
    time: 01:00:00
    cpus-per-task: 10

# Module 1 - Alignments
################################################################################

build_genome_indices:
    job-name: build_genome_indices
    time: 08:00:00
    mem-per-cpu: 16000
    cpus-per-task: 20

star_align_raw_reads:
    job-name: star_align_raw_reads
    time: 04:00:00
    cpus-per-task: 20
    
star_align_trimmed_reads:
    job-name: star_align_trimmed_reads
    time: 04:00:00
    cpus-per-task: 20
    
# Module 2 - Reporting
################################################################################
R_finalReport:
    time: 0-01:00:00
    job-name: Finalreport
    mem-per-cpu: 64000